### ISSUE TITLE
Add pagination for large output when using table mode

### ISSUE THREAD

**Issue by pederhan** [pederhan/harbor-cli#20]
If using table mode, we should add a pagination mode (maybe even forwards/backwards pagination?), so that users can more easily navigate the results. Basic pagination should be easy enough to implement with Rich, but more advanced pagination functionality could be implemented with [Textual](https://textual.textualize.io/getting_started/). 

Pagination should be toggleable, and the number of results per page should be configurable.

```toml
[output.pagination]
enabled = true
# static (int arg)
page_size = 10
# implicit dynamic page size if omitted
# ...
```
